### ISSUE TITLE
chialog.mtaill fails to compile

### ISSUE THREAD

**Issue by tiagom101** [ytx1991/ChiaMonitor#2]
```
$ mtail --progs chialog.mtail --logs ~/.chia/mainnet/log/debug.log -compile_only

E0429 09:50:23.689628 1064409 main.go:151] Compile encountered errors:
compile failed for chialog.mtail:
chialog.mtail:8:11-24: syntax error: unexpected ID, expecting NL
```

**Comment by ytx1991** [comment]
I'm not sure if you can use the file name for the --progs. It should be the folder of your *.mtail files.

**Comment by tiagom101** [comment]
I get the same error if I run it on that folder,

`$mtail --compile_only --progs ./
E0429 13:39:02.040583   39699 main.go:151] Compile encountered errors:
compile failed for chialog.mtail:
chialog.mtail:8:11-24: syntax error: unexpected ID, expecting NL`

**Comment by ytx1991** [comment]
interesting, you didn't change the chialog.mtail right? Are you using the mtail in this repo?

**Comment by tiagom101** [comment]
I haven't changed the chailog.mtail, I'm using mtail from the apt repository,
`mtail version 3.0.0~rc24.1 git revision 3.0.0~rc24.1-1ubuntu1 go version go1.10.4 go arch amd64 go os linux`

**Comment by ytx1991** [comment]
I'm using rc45 https://github.com/google/mtail/releases. May be you can try it.

**Comment by tiagom101** [comment]
That was it, 3.0.0. rc45 fixed it!

**Comment by ytx1991** [comment]
Good to know
