### ISSUE TITLE
grafana_dashboard_en.json missing datasource reference

### ISSUE THREAD

**Issue by jshank** [ytx1991/ChiaMonitor#4]
I did a global find and replace on [grafana_dashboard_en.json](https://github.com/ytx1991/ChiaMonitor/blob/main/grafana_dashboard_en.json) in vscode and it's working properly now.  

**Find**:  `"datasource": null`
**Replace**: `"datasource": "Chia"`

Make sure to create the datasource in Grafana _before_ you import the dashboard.

**Comment by ytx1991** [comment]
If you use null as data source it will use the default the data source.

**Comment by jshank** [comment]
Since not everyone is going to use Grafana just for this solution, wouldn't it make more sense to make the dashboard JSON more prescriptive by defining the datasource?

**Comment by RondoChen** [comment]
i had also found this case, and i agree with @jshank .
