### ISSUE TITLE
Missing some data

### ISSUE THREAD

**Issue by VercauterenK** [ytx1991/ChiaMonitor#6]
Hi,

I've finally get it working partial, i am missing expect xch per day and earned and expected time to win and netspace.

Anyone know how to fix that been trying for 16 hours straight (going a bit nut now)

Thanks

**Comment by ytx1991** [comment]
some features need you node fully synced

**Comment by VercauterenK** [comment]
Its fully synced i geus beceause its farming. Really dont know it anymore :-(

**Comment by VercauterenK** [comment]
kevin@kevin-X570-AORUS-PRO:~$ sudo su
root@kevin-X570-AORUS-PRO:/home/kevin# /root/chia-blockchain/venv/bin/chia farm summary
Farming status: Farming
Total chia farmed: 0.0
User transaction fees: 0.0
Block rewards: 0.0
Last height farmed: 0
Plot count: 0
Total size of plots: 0.000 GiB
Estimated network space: 5968.663 PiB
Expected time to win: Unknown
Note: log into your key using 'chia wallet show' to see rewards for each key
root@kevin-X570-AORUS-PRO:/home/kevin#

**Comment by VercauterenK** [comment]
this is my mtail response
farmlog.mtail.xch_count 0 1621226385
farmlog.mtail.last_farm_height 0 1621226385
chialog.mtail.number_of_challenges 17 1621233594
chialog.mtail.total_plots 0 1621233594
chialog.mtail.eligible_plots 0 1621233594
chialog.mtail.proofs_found 0 1621233594
chialog.mtail.check_duration.bin_0.25 0 1621233594
chialog.mtail.check_duration.bin_0.75 0 1621233594
chialog.mtail.check_duration.bin_inf 0 1621233594
chialog.mtail.check_duration.bin_2.5 0 1621233594
chialog.mtail.check_duration.bin_5 0 1621233594
chialog.mtail.check_duration.bin_10 0 1621233594
chialog.mtail.check_duration.bin_0.1 17 1621233594
chialog.mtail.check_duration.bin_0.5 0 1621233594
chialog.mtail.check_duration.bin_1 0 1621233594
chialog.mtail.check_duration.count 17 1621233594
chialog.mtail.check_duration 0.04408000000000001 1621233594
farmlog.mtail.network_space 5950.92 1621226385

**Comment by ytx1991** [comment]
Your total plots is 0? Do you have any plots?

**Comment by VercauterenK** [comment]
+- 900 on the harverster that are showing up in the stats

**Comment by ytx1991** [comment]
Is your harvester running? Did you enable the INFO log?

**Comment by VercauterenK** [comment]
yes

**Comment by VercauterenK** [comment]
https://www.mobilrent.be/monitor.png

**Comment by ytx1991** [comment]
check if there is ~/.chia/mainnet/log/farmer_summary.log and the content looks valid

**Comment by VercauterenK** [comment]
Yes the content is valid even in mtail graph I can see network size

Verstuurd vanaf mijn iPhone

**Comment by ytx1991** [comment]
Did you modify the dashboard? I don't know which part is going wrong now.

**Comment by VercauterenK** [comment]
No nothing changed he can’t find ntwork space

Verstuurd vanaf mijn iPhone

**Comment by VercauterenK** [comment]
Can I get the network space from somewhere else?

**Comment by VercauterenK** [comment]
All the data from farmlog.mtail the dashboard can't get. the rest i can get through the dash.

farmlog.mtail.last_farm_height 0 1621234584
chialog.mtail.number_of_challenges 28 1621241825
chialog.mtail.total_plots 0 1621241825
chialog.mtail.eligible_plots 0 1621241825
chialog.mtail.proofs_found 0 1621241825
chialog.mtail.check_duration.bin_1 0 1621241825
chialog.mtail.check_duration.bin_10 0 1621241825
chialog.mtail.check_duration.bin_0.25 0 1621241825
chialog.mtail.check_duration.bin_0.75 0 1621241825
chialog.mtail.check_duration.bin_2.5 0 1621241825
chialog.mtail.check_duration.bin_5 0 1621241825
chialog.mtail.check_duration.bin_inf 0 1621241825
chialog.mtail.check_duration.bin_0.1 28 1621241825
chialog.mtail.check_duration.bin_0.5 0 1621241825
chialog.mtail.check_duration.count 28 1621241825
chialog.mtail.check_duration 0.04059 1621241825
farmlog.mtail.network_space 5953.32 1621234584
farmlog.mtail.xch_count 0 1621234584

**Comment by ytx1991** [comment]
You have network space
farmlog.mtail.network_space 5953.32 1621234584

**Comment by VercauterenK** [comment]
yeah but the dashboard cant read it

**Comment by VercauterenK** [comment]
Where do you give the var to prometheus or how can i check that they are in promotheus

**Comment by VercauterenK** [comment]
Found my problem in the prometheus you ask for the harvesters ip addresses but you also need to give the farmer Ip.

I have 5 harvesters that are connected to 1 farmer so all i needed to do was also give the farmer ip address
